using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace osuStats.Migrations
{
    /// <inheritdoc />
    public partial class AddScoresPartitioning : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_Scores",
                table: "Scores"); 
            
            migrationBuilder.DropIndex(
                name: "IX_Scores_Mode",
                table: "Scores");

            migrationBuilder.DropIndex(
                name: "IX_Scores_Pp",
                table: "Scores");

            migrationBuilder.DropIndex(
                name: "IX_Scores_Grade",
                table: "Scores");

            migrationBuilder.DropIndex(
                name: "IX_Scores_Mods",
                table: "Scores");

            migrationBuilder.DropIndex(
                name: "IX_Scores_Date",
                table: "Scores");

            migrationBuilder.Sql(@"
                ALTER TABLE ""Scores""
                RENAME TO ""Scores_legacy"";

                ALTER TABLE ""Scores_legacy""
                ALTER COLUMN ""Id"" DROP IDENTITY;

                CREATE TABLE ""Scores""
                (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""UserId"" integer NOT NULL,
                    ""BeatmapId"" integer NOT NULL,
                    ""Grade"" integer NOT NULL,
                    ""Accuracy"" double precision NOT NULL,
                    ""Combo"" integer NOT NULL,
                    ""Mods"" jsonb NOT NULL,
                    ""Date"" timestamp with time zone NOT NULL,
                    ""TotalScore"" integer NOT NULL,
                    ""Pp"" double precision,
                    ""Mode"" integer NOT NULL,
                    ""HasReplay"" boolean NOT NULL,
                    ""IsPerfectCombo"" boolean NOT NULL,
                    CONSTRAINT ""PK_Scores"" PRIMARY KEY (""Id"", ""Date"")
                ) PARTITION BY RANGE (""Date"");

                ALTER TABLE ""Scores""
                ATTACH PARTITION ""Scores_legacy"" DEFAULT;
            ");

            migrationBuilder.CreateIndex(
                name: "IX_Scores_Mode",
                table: "Scores",
                column: "Mode");

            migrationBuilder.CreateIndex(
                name: "IX_Scores_Pp",
                table: "Scores",
                column: "Pp");

            migrationBuilder.CreateIndex(
                name: "IX_Scores_Grade",
                table: "Scores",
                column: "Grade");

            migrationBuilder.CreateIndex(
                    name: "IX_Scores_Mods",
                    table: "Scores",
                    column: "Mods")
                .Annotation("Npgsql:IndexMethod", "gin");

            migrationBuilder.CreateIndex(
                    name: "IX_Scores_Date",
                    table: "Scores",
                    column: "Date")
                .Annotation("Npgsql:IndexMethod", "brin");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // if it fails it fails gg
        }
    }
}
