// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using osuStats.Database;

#nullable disable

namespace osuStats.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260417104300_AddScores")]
    partial class AddScores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "hstore");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("osuStats.Database.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer");

                    b.Property<int>("Combo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<bool>("HasReplay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPerfectCombo")
                        .HasColumnType("boolean");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<double?>("Pp")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Mode");

                    b.HasIndex("Pp");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("osuStats.Database.Models.Score", b =>
                {
                    b.OwnsMany("osuStats.OsuApi.Models.Mod", "Mods", b1 =>
                        {
                            b1.Property<long>("ScoreId")
                                .HasColumnType("bigint");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Acronym")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasAnnotation("Relational:JsonPropertyName", "acronym");

                            b1.Property<Dictionary<string, string>>("Settings")
                                .IsRequired()
                                .HasColumnType("hstore")
                                .HasAnnotation("Relational:JsonPropertyName", "settings");

                            b1.HasKey("ScoreId", "__synthesizedOrdinal");

                            b1.ToTable("Scores");

                            b1
                                .ToJson("Mods")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ScoreId");
                        });

                    b.Navigation("Mods");
                });
#pragma warning restore 612, 618
        }
    }
}
